baseURL: https://sdjmchattie.github.io/
languageCode: en-gb
title: IsCoding
theme: ananke
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 3
taxonomies:
  tag: tags
preserveTaxonomyNames: true
