baseURL: https://sdjmchattie.github.io/
languageCode: en-gb
title: IsCoding
theme: hugo-profile
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 3
taxonomies:
  tag: tags
preserveTaxonomyNames: true
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
