baseURL: https://sdjmchattie.github.io/
languageCode: en-gb
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 3
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
pagination:
  pagerSize: 9
permalinks:
  page:
    posts: /posts/:year/:month/:day/:slug/
preserveTaxonomyNames: true
services:
  googleAnalytics:
    id: G-34WM07R68F
taxonomies:
  tag: tags
theme: hugo-profile
title: IsCoding
