graph TD;
	__start__([<p>START</p>]):::first
	fetch_weather(fetch_weather)
	fetch_attractions(fetch_attractions)
	write_brief(write_brief)
	__end__([<p>END</p>]):::last
	__start__ --> fetch_weather;
	__start__ --> fetch_attractions;
	fetch_weather --> write_brief;
	fetch_attractions --> write_brief;
	write_brief --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
