name: Merge Scheduled Pull Requests

on:
  # Runs when a pull request is opened, edited, or synchronized
  pull_request:
    types:
      - opened
      - edited
      - synchronize

  # Runs every day at 08:30
  schedule:
    - cron: 30 8 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge_schedule:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Do merge checks
        id: merge-schedule
        uses: gr2m/merge-schedule-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      merged_pull_requests: ${{ steps.merge-schedule.outputs.merged_pull_requests }}
      hello_array: '["hello"]'
      always_true: true
  display_outputs:
    runs-on: ubuntu-latest
    needs: merge_schedule
    steps:
      - name: Display outputs
        run: echo "${{ toJson(needs.merge_schedule.outputs) }}"
      - name: Display hello array
        run: echo "${{ toJSON(needs.merge_schedule.outputs.hello_array) }}"
      - name: Check for value
        run: echo "${{ toJSON(needs.merge_schedule.outputs.hello_array)[0] == 'hello' }}"
      - name: Dump GitHub Actions context
        run: |
          echo "Dumping context for debugging"
          env
  deploy_website:
    needs: merge_schedule

    # Sets permissions of the GITHUB_TOKEN to be able to call the deployment workflow
    permissions:
      contents: read
      pages: write
      id-token: write

    if: ${{ toJSON(needs.merge_schedule.outputs.hello_array)[0] != null }}
    uses: ./.github/workflows/hugo.yaml
