name: Merge Scheduled Pull Requests

on:
  # Runs when a pull request is opened, edited, or synchronized
  pull_request:
    types:
      - opened
      - edited
      - synchronize

  # Runs every day at 08:30
  schedule:
    - cron: 30 8 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge_schedule:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Do merge checks
        id: merge-schedule
        uses: gr2m/merge-schedule-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy website
        if: ${{ fromJson(steps.merge-schedule.outputs.merged_pull_requests)[0] != null }}
        uses: ./.github/workflows/hugo.yaml
