name: Merge Scheduled Pull Requests

on:
  # Runs when a pull request is opened, edited, or synchronized
  pull_request:
    types:
      - opened
      - edited
      - synchronize

  # Runs every day at 08:30
  schedule:
    - cron: 30 8 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: gr2m/merge-schedule-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
